language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt update && sudo apt install -y graphviz
  - sudo apt install -y python3 python3-pip python3-setuptools
  - sudo pip3 install blockdiag seqdiag actdiag nwdiag
  - gem update --system && gem install bundler
