language: ruby

dist: bionic

cache:
  apt: true
  bundler: true

jobs:
  fast_finish: true
  allow_failures:
    - name: Cabal Packages
      env: DIAGRAM=cabal
      cache:
        directories:
          - "$HOME/.cabal"
      addons:
        apt:
          update: true
          packages:
            - cabal-install
      before_install:
        - cabal update
        - cabal install erd
  include:
    - name: Apt Packages
      env: DIAGRAM=apt
      addons:
        apt:
          update: true
          packages:
            - graphviz

    - name: Cargo Packages
      env: DIAGRAM=cargo
      cache: cargo
      addons:
        apt:
          update: true
          packages:
            - cargo
      before_install:
        - cargo install svgbob_cli

    - name: Java Packages
      env: DIAGRAM=java
      addons:
        apt:
          update: true
          packages:
            - default-jre-headless

    - name: Npm Packages
      env: DIAGRAM=npm
      cache: npm
      addons:
        apt:
          update: true
          packages:
            - npm
      before_install:
        - npm install -g mermaid.cli nomnoml state-machine-cat
        - npm install -g vega-cli vega-lite wavedrom-cli

    - name: Pip Packages
      env: DIAGRAM=pip
      cache: pip
      addons:
        apt:
          update: true
          packages:
            - libpython3-dev
            - libpango1.0-dev
            - python3-pip
            - python3-setuptools
            - python3-cairo
            - python3-gi
      before_install:
        - pip3 install blockdiag seqdiag actdiag nwdiag syntrax

script: bundle exec rake 'dummy_site:build[$DIAGRAM]'