dist: bionic

language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

cache:
  apt: true
  bundler: true
  npm: true
  pip: true
  directories:
    - "$HOME/.cabal"

addons:
  apt:
    update: true
    packages:
      - build-essential
      - git
      - graphviz
      - default-jre-headless
      - cabal-install
      - gnuplot
      - graphviz
      - npm
      - libpython3-dev
      - libpango1.0-dev
      - python3-pip
      - python3-setuptools
      - python3-cairo
      - python3-gi

install:
  - npm install -g mermaid.cli state-machine-cat wavedrom-cli
  - pip3 install blockdiag seqdiag actdiag nwdiag syntrax
  - gem update -N --system && gem install -N bundler
  - cabal update && cabal install erd
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake dummy_site
