language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

addons:
  apt:
    packages:
      - cabal-install
      - default-jre
      - gnuplot
      - graphviz
      - npm
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - sudo cabal update && sudo cabal install erd
  - sudo gem update --system && sudo gem install bundler
  - sudo npm install -g mermaid.cli state-machine-cat wavedrom-cli 
  - sudo pip3 install blockdiag seqdiag actdiag nwdiag syntrax