language: ruby

dist: bionic

cache:
 - apt
 - bundler
 - npm

rvm:
  - 2.5
  - 2.6
  - 2.7

addons:
  apt:
    update: true
    packages:
      - build-essential
      - git
      - cabal-install
      - cargo
      - default-jre-headless
      - graphviz
      - npm
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libgif-dev
      - libgtk-3-0
      - libx11-xcb1
      - libxcomposite1
      - libxrandr2
      - libxss1
      - libpango1.0-dev
      - libpython3-dev
      - python3-pip
      - python3-setuptools
      - python3-cairo
      - python3-gi
      - python3-gi-cairo
      - ruby-full

before_install:
  - sudo cargo install --root /usr/local svgbob_cli
  - gem update --no-document --system
  - gem install --no-document bundler
  - npm install -g --silent mermaid.cli nomnoml state-machine-cat vega-cli vega-lite wavedrom-cli
  - pip3 install syntrax blockdiag seqdiag actdiag nwdiag

script: bundle exec rake
