language: ruby

os: linux

dist: bionic

cache:
 bundler: true
 cargo: true
 pip: true

rvm:
  - 2.7
  - 2.6
  - 2.5

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/3.8.gemfile

jobs:
  fast_finish: true

before_install:
  - cargo install svgbob_cli
  - gem update -N --system
  - gem install -N bundler
  - npm install -g --silent mermaid.cli nomnoml state-machine-cat vega-cli vega-lite wavedrom-cli
  - pip3 install syntrax blockdiag seqdiag actdiag nwdiag

install: bundle install --jobs 8 --retry 3

before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"

script: bundle exec rake

addons:
  apt:
    update: true
    packages:
      - cabal-install
      - cargo
      - graphviz
      - npm
      - libgif-dev
      - libpango1.0-dev
      - python3-pip
      - python3-setuptools
      - python3-cairo
      - python3-gi-cairo
